
networks:
  my-network:


services:
  frontend:
    build:
      context: ./frontend
    ports:
      - "3000:80"

  backend:
    build:
      context: ./backend
    restart: always
    ports:
      - "8082:8081"
    networks:
      - my-network
    depends_on:
      - mysql-db

  mysql-db:
    image: mysql
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: 'counterdb'
      MYSQL_ROOT_PASSWORD: '85C1aa39.'
    networks:
      - my-network
